### ISSUE TITLE
OHEM on VGG

### ISSUE THREAD

**Issue by busyboxs** [ChaoPei/faster-rcnn-pedestrian-detection#1]
hello, thank you for sharing the repo. Here I have two questions:
1. did you test the ohem on vgg, and what about the result?
2. what does VGG_CONCAT mean?

**Comment by ChaoPei** [comment]
@busyboxs Hi, I did test OHEM on VGG, it seems not working in faster r-cnn

VGG_CONCAT is just a push error, now it's deleted.
